// Publish only browser assets; Python sources and local settings stay private.
const fs = require('node:fs');
const path = require('node:path');
const output = path.join(__dirname, 'public');
const readData = name => JSON.parse(fs.readFileSync(path.join(__dirname,'data',name),'utf8').replace(/^\uFEFF/,''));
const world = readData('world-boundaries.geojson');
const boundaries = {type:'FeatureCollection',features:world.features.map(feature => ({type:'Feature',properties:{name:feature.properties.NAME,code:feature.properties.ISO_A2_EH},geometry:feature.geometry}))};
fs.writeFileSync(path.join(__dirname,'data/locations.js'), '// Generated by build-static.cjs; source: local JSON and Natural Earth.\nwindow.DCMDLocationData = '+JSON.stringify({provinces:readData('turkiye.json'),countries:readData('countries.json'),boundaries})+';\n');
fs.mkdirSync(output, { recursive: true });
// Remove retired player assets from an existing local build as well.
for (const retired of ['music.css', 'music.js', 'music-services.js']) {
  fs.rmSync(path.join(output, retired), {force:true});
}
for (const file of [
  'index.html', 'style.css', 'script.js', 'weather.css', 'weather.js', 'weather-direct.js',
  'languages.js', 'languages.css',
  'dcmd-enhance.css', 'dcmd-enhance.js', 'dcmd-system.css', 'dcmd-editorial.css',
  'dcmd-reference.css', 'dcmd-reference.js', 'dcmd-boutique.css', 'dcmd-boutique.js', 'campaign-playlist.js',
  'data', 'images', 'vendor', 'policies', 'commerce.js'
]) {
  fs.cpSync(path.join(__dirname, file), path.join(output, file), { recursive: true });
}
